name: CI/CD Pipeline

# Trigger workflow on push or pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs to run in this workflow
jobs:
  # This job installs dependencies and runs tests
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  # This job deploys your app after the build is successful
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures the deploy job runs only if the build job is successful

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        run: |
          echo "Deploying application..."
          # Add your deploy commands here
          # Example: scp files to your server, use AWS CLI, etc.
